build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-external-libs"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-internal-libs"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-mxchip-azureiot"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-mxchip-filesystem"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-mxchip-sensors"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-mxchip-wifiscan"
    - PLATFORMIO_PROJECT_DIR: "examples/cmsis-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/libopencm3-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-dsp"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-events"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-filesystem"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-rtos"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-rtos-ethernet"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-rtos-ethernet-tls"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-rtos-semaphore"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-serial"
    - PLATFORMIO_PROJECT_DIR: "examples/spl-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/stm32cube-hal-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/stm32cube-ll-blink"

install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=%PATH%;C:\Python27\Scripts
  - cmd: pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - cmd: platformio platform install file://.

test_script:
  - cmd: platformio run -d %PLATFORMIO_PROJECT_DIR%

notifications:
  - provider: Slack
    incoming_webhook:
      secure: E9H0SU0Ju7WLDvgxsV8cs3J62T3nTTX7QkEjsczN0Sto/c9hWkVfhc5gGWUkxhlD975cokHByKGJIdwYwCewqOI+7BrcT8U+nlga4Uau7J8=
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
